version: '3'
services:

  sri-agent:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      APPLICATION_URL: ${APPLICATION_URL:-http://localhost:5000}
      CONFIG_ROOT: ../config
      ENVIRONMENT: ${ENVIRONMENT:-default}
      ENABLE_GUNICORN: ${ENABLE_GUNICORN:-}
      INDY_LEDGER_URL: ${LEDGER_URL:-http://localhost:9000}
      FORMS: ${FORMS:-}
      ISSUERS: ${ISSUERS:-}
      LOG_LEVEL: ${LOG_LEVEL:-}
      POSTGRESQL_WALLET_HOST: ${POSTGRESQL_WALLET_HOST}
      POSTGRESQL_WALLET_PORT: ${POSTGRESQL_WALLET_PORT}
      POSTGRESQL_WALLET_USER: ${POSTGRESQL_USER}
      POSTGRESQL_WALLET_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_WALLET_ADMIN_PASSWORD: ${POSTGRESQL_ADMIN_PASSWORD}
      SRI_URL: ${SRI_URL:-}
      TOB_API_URL: ${TOB_API_URL:-}
      TOB_APP_URL: ${TOB_APP_URL:-}
      WALLET_ENCRYPTION_KEY: ${WALLET_ENCRYPTION_KEY}
      WALLET_SEED_PSPC: ${WALLET_SEED_PSPC:-}
      WALLET_SEED_CISD: ${WALLET_SEED_CISD:-}
      WALLET_SEED_INAC: ${WALLET_SEED_INAC:-}
      WALLET_TYPE: ${WALLET_TYPE}
      WEB_BASE_HREF: ${WEB_BASE_HREF:-/}
    external_links:
       - sritob_tob-api_1:tob-api
    depends_on:
        - sri-wallet-db
    networks:
      - tob
    ports:
      - ${WEB_HTTP_PORT:-5000}:8000
    entrypoint: >
      /bin/bash -c "
        echo sleeping ...;
        sleep 5;
        ../docker/docker-entrypoint.sh;"

  sri-wallet-db:
    image: registry.access.redhat.com/rhscl/postgresql-95-rhel7:9.5
    environment:
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_ADMIN_PASSWORD=${POSTGRESQL_ADMIN_PASSWORD}
    networks:
      - tob
    ports:
      - 5434:5432
    volumes:
      - wallet-db:/var/lib/pgsql/data

volumes:
  wallet-db:

networks:
  tob:
    external:
      name: sritob_tob
