- name: pspc-sri.gc-vendor-credential
  version: 1.0.5
  attributes:
    - legal_entity_id
    - sri_record_id
    - status
    - legal_name
    - org_type
    - addressee
    - address_line_1
    - address_line_2
    - city
    - province
    - postal_code
    - country
    - effective_date
    - end_date

- name: pspc-sri.green-supplier
  version: 1.0.0
  attributes:
    - legal_entity_id
    - status
    - effective_date
    - end_date

- name: pspc-sri.women-owned-supplier
  version: 1.0.0
  attributes:
    - legal_entity_id
    - status
    - effective_date
    - end_date

- name: pspc-sri.gc-vendor-performance
  version: 1.0.0
  attributes:
    - legal_entity_id
    - score
    - status
    - effective_date
    - end_date

- name: pspc-sri.designated-organization-screening
  version: 1.0.0
  attributes:
    - legal_entity_id
    - type
    - status
    - effective_date
    - end_date

- name: pspc-sri.facility-security-clearance
  version: 1.0.0
  attributes:
    - legal_entity_id
    - level
    - status
    - effective_date
    - end_date

- name: isc-inac.aboriginal-business
  version: 1.0.0
  attributes:
    - legal_entity_id
    - status
    - effective_date
    - end_date
